### ISSUE TITLE
Many images are missing

### ISSUE THREAD

**Issue by ShenJiahuan** [drop-sjtu/dropSJTU-BulletinBoardService#1]
Many images are missing in `doc/Google Java Style Guide.md`.
For example:
<img width="235" alt="Screen Shot 2019-05-11 at 09 11 57" src="https://user-images.githubusercontent.com/15841780/57563153-f1dfa800-73cc-11e9-8158-cbc408eb9c39.png">

**Comment by eyeKill** [comment]
Bugs when converting HTML to Markdown in Typora.
Fix: remove all unnecessary images and external links.
